import { currentLanguage, initI18n } from "../src/i18n.js";
import { finishSiteLoading, setSiteLoadingProgress } from "../src/site-ui.js";
import { parseVox } from "../src/vox/ncm.js";
import "./style.css";
import "../src/site-header.css";

const fallbackCopy = {
  meta: {
    title: "NCFM | Fourier Chain 3D Assets",
    description: "NCFM explains how NiceChunk stores 3D game items as compact Fourier/function code directly on-chain instead of relying on external 3D asset files or IPFS metadata.",
  },
  nav: { aria: "Primary navigation" },
  hero: {
    eyebrow: "NICECHUNK FOURIER MODEL",
    title: "3D game items as chain-readable functions, not asset files.",
    body: "NCFM is the research direction behind NiceChunk's next asset layer: store a tiny Fourier/function description on-chain, then let the client deterministically reconstruct the voxel item through RPC. No GLB file, no mutable JSON, no IPFS gateway dependency.",
    ctaLab: "Open function lab",
    ctaCompare: "Compare storage",
    ctaNcm: "Back to NCM",
    proofAria: "NCFM guarantees",
    proof1: "Deterministic reconstruction",
    proof2: "Short chain payload",
    proof3: "No external asset host",
  },
  payload: {
    aria: "NCFM compact payload",
    label: "Example chain payload",
    meshFiles: "mesh files",
    ipfsLinks: "IPFS links",
    rpcRead: "RPC read",
  },
  thesis: {
    aria: "Storage thesis",
    asset: { title: "Traditional game asset", body: "A wallet or NFT points to metadata, the metadata points to a file, and the file must remain available somewhere outside the chain." },
    ipfs: { title: "IPFS-style permanence", body: "Better than a normal server, but the game still depends on external content routing, pinning, gateways, and metadata conventions." },
    ncfm: { title: "NCFM function asset", body: "The item is a deterministic function payload. Ownership, rendering rules, verification hash, and visual identity can live together in account data." },
  },
  principle: {
    eyebrow: "PRINCIPLE DIAGRAM",
    title: "Store the equation. Rebuild the object.",
    body: "NCFM treats a 3D item as a deterministic field instead of a static file. The chain stores the smallest canonical record: seed, quantized coefficients, palette rules, grid limits, and a verifier hash. The browser expands that record into the visible item.",
    diagramAria: "NCFM equation to voxel pipeline",
    source: { title: "Chain payload" },
    function: { title: "Canonical functions" },
    sampler: { title: "Deterministic sampler" },
    output: { title: "Renderable object" },
    cards: {
      formula: {
        kicker: "Formula",
        title: "A shape is a field acceptance rule.",
        body: "For every coordinate, the client asks the same question: does this point satisfy the agreed functions? Accepted coordinates become material voxels.",
      },
      hash: {
        kicker: "Hash",
        title: "The visible model can be verified.",
        body: "Because sampling order, grid bounds, quantization, and palette are canonical, the generated voxel set can produce a stable model hash.",
      },
      chain: {
        kicker: "Chain",
        title: "The chain stores identity, not bulk geometry.",
        body: "The account does not need to carry a heavy mesh. It only needs the record required to regenerate and verify the object forever.",
      },
    },
  },
  lab: {
    eyebrow: "FUNCTION INTERSECTION LAB",
    title: "A 3D item generated by two compact functions.",
    body: "This demo uses a pickaxe because the shape is easy to read: an XY function defines the outline, material bands, and color; a Z function defines thickness. Only coordinates accepted by both functions become voxels.",
    voxelCount: "Voxels",
    copy: "Copy payload",
    visualLabel: "Live reconstruction",
    pause: "Pause",
    resume: "Resume",
    terms: "Fourier terms",
    depth: "Z thickness",
    canvasAria: "NCFM Fourier voxel reconstruction preview",
    copied: "Copied",
    importVox: "Import VOX",
    defaultModel: "Using function-generated pickaxe.",
    importedPrefix: "Imported VOX",
    importFailed: "Failed to import VOX",
    phases: ["Fourier curve", "XY field", "Z thickness", "Voxel output"],
  },
  stage: {
    xy: {
      title: "FXY: Fourier line drawing on the XY plane",
      body: "First, the item is only a 2D function. Fourier descriptors reconstruct the pickaxe outline as a curve over time, proving that the shape can be represented by coefficients instead of an image file.",
    },
    intersection: {
      title: "FXY × FZ: intersect the XY field with a Z thickness field",
      body: "The second function turns the 2D outline into a volume. Blue marks the XY projection, gold marks the Z thickness rule, and green marks coordinates accepted by both functions.",
    },
    voxel: {
      title: "Intersection result: final 3D voxel pickaxe",
      body: "The final item is not loaded from a mesh. The client scans deterministic coordinates, keeps only the points accepted by both functions, applies material color, and renders the resulting voxel model.",
    },
    note: "Key point: the chain stores the function seed, coefficients, parameters, palette, and verifier hash. The visible 3D model is recreated from code, not downloaded as a 3D file.",
  },
  pipeline: {
    aria: "NCFM verification pipeline",
    eyebrow: "CHAIN VERIFICATION PIPELINE",
    title: "What the client and contract can agree on.",
    body: "NCFM keeps the chain payload small by making the heavy visual reconstruction a deterministic client operation. The important part is that all clients derive the same model hash from the same code.",
    read: { title: "Read", body: "Fetch the payload from a PDA or asset account through RPC." },
    decode: { title: "Decode", body: "Parse seed, palette, Fourier coefficients, field parameters, and verifier hash." },
    sample: { title: "Sample", body: "Run the canonical sampler over the agreed voxel grid." },
    render: { title: "Render", body: "Build a mesh or voxel instance buffer locally and compare the deterministic model hash." },
  },
  meaning: {
    eyebrow: "TECHNICAL MEANING",
    title: "Why this matters for an open on-chain game.",
    body: "The goal is not only compression. The goal is to make game assets transparent, permanent, cheaply readable, and reproducible by any client or explorer without trusting a private asset server.",
    permanent: { title: "Permanent", body: "If the payload remains on-chain, the asset definition remains available with the account history." },
    open: { title: "Open", body: "Players can inspect the exact function code and parameters used to reconstruct the item." },
    fast: { title: "Fast", body: "A short RPC read replaces multiple metadata, gateway, and file fetches." },
    portable: { title: "Portable", body: "The same compact record can be interpreted by games, explorers, crafting tools, and future clients." },
  },
  spec: {
    aria: "NCFM technical sketch",
    model: {
      eyebrow: "DATA MODEL",
      title: "A tiny text record with deterministic meaning.",
      item1: "Header: version, item class, grid size, quantization.",
      item2: "Functions: Fourier descriptors, signed distance segments, harmonic thickness fields.",
      item3: "Palette: compact material IDs and derived color rules.",
      item4: "Verifier: model hash generated by canonical sampling.",
    },
    cost: {
      eyebrow: "WHY IT MATTERS",
      title: "On-chain 3D becomes a code problem, not a file-hosting problem.",
      body: "If the item can be described as a short function, the chain only stores the minimum seed and parameters. The world can still render rich 3D assets while keeping storage cost predictable and publicly auditable.",
      link: "View older Fourier voxel demo",
    },
  },
};

const dictionaries = {
  en: fallbackCopy,
  "zh-Hans": {
    meta: { title: "NCFM | 傅里叶链上 3D 资产", description: "NCFM 用来解释 NiceChunk 如何把 3D 游戏物品压缩为链上可读的傅里叶/函数代码，而不是依赖外部 3D 资产文件或 IPFS 元数据。" },
    nav: { aria: "主导航" },
    hero: { eyebrow: "NICECHUNK 傅里叶模型", title: "3D 游戏物品可以是链上可读函数，而不是资产文件。", body: "NCFM 是 NiceChunk 下一代资产层的研究方向：把极短的傅里叶/函数描述储存在链上，客户端通过 RPC 读取后确定性还原体素物品。不需要 GLB 文件，不需要可变 JSON，也不依赖 IPFS 网关。", ctaLab: "打开函数实验室", ctaCompare: "对比储存方式", ctaNcm: "返回 NCM", proofAria: "NCFM 保证", proof1: "确定性重建", proof2: "极短链上载荷", proof3: "不依赖外部资产托管" },
    payload: { aria: "NCFM 紧凑载荷", label: "链上载荷示例", meshFiles: "模型文件", ipfsLinks: "IPFS 链接", rpcRead: "RPC 读取" },
    thesis: { aria: "储存理念", asset: { title: "传统游戏资产", body: "钱包或 NFT 指向元数据，元数据再指向文件，而文件必须在链外某个位置持续可用。" }, ipfs: { title: "IPFS 式永久性", body: "它比普通服务器更好，但游戏仍然依赖外部内容路由、固定、网关和元数据约定。" }, ncfm: { title: "NCFM 函数资产", body: "物品是一段确定性的函数载荷。所有权、渲染规则、验证哈希和视觉身份可以一起存在账户数据里。" } },
    principle: { eyebrow: "原理图", title: "储存方程，重建物品。", body: "NCFM 把 3D 物品视为确定性的场，而不是静态文件。链上只保存最小 canonical 记录：种子、量化系数、调色板规则、网格边界和验证哈希。浏览器再把这段记录展开成可见物品。", diagramAria: "NCFM 从方程到体素的流程", source: { title: "链上载荷" }, function: { title: "Canonical 函数" }, sampler: { title: "确定性采样器" }, output: { title: "可渲染物品" }, cards: { formula: { kicker: "公式", title: "形状就是一个场接受规则。", body: "对每个坐标，客户端都问同一个问题：这个点是否满足约定函数？被接受的坐标才会成为材质体素。" }, hash: { kicker: "哈希", title: "用户看到的模型可以被验证。", body: "采样顺序、网格边界、量化方式和调色板都是 canonical 的，因此生成的体素集合可以得到稳定模型哈希。" }, chain: { kicker: "链上", title: "链上储存身份，而不是大体积几何。", body: "账户不需要携带沉重 mesh，只需要保存能永久重建和验证物品的必要记录。" } } },
    lab: { eyebrow: "函数相交实验室", title: "由两个紧凑函数生成的 3D 物品。", body: "这里用镐子演示，因为形状容易理解：XY 函数定义轮廓、材质分区和颜色；Z 函数定义厚度。只有同时被两个函数接受的坐标才会成为体素。", voxelCount: "体素", copy: "复制载荷", visualLabel: "实时重建", pause: "暂停", resume: "继续", terms: "傅里叶项", depth: "Z 厚度", canvasAria: "NCFM 傅里叶体素重建预览", copied: "已复制", importVox: "导入 VOX", defaultModel: "正在使用函数生成的镐子。", importedPrefix: "已导入 VOX", importFailed: "VOX 导入失败", phases: ["傅里叶曲线", "XY 场", "Z 厚度", "体素输出"] },
    stage: {
      xy: { title: "FXY：XY 平面上的傅里叶线条绘制", body: "第一步只看二维函数。傅里叶描述符把镐子的轮廓还原成随时间绘制的曲线，证明形状可以由系数表达，而不是依赖图片或模型文件。" },
      intersection: { title: "FXY × FZ：XY 场与 Z 厚度场相交", body: "第二个函数把二维轮廓变成体积。蓝色表示 XY 投影，金色表示 Z 轴厚度规则，绿色表示两个函数同时接受的坐标。" },
      voxel: { title: "相交结果：最终 3D 体素镐子", body: "最终物品不是从 mesh 读取。客户端扫描确定性坐标，只保留同时满足两个函数的位置，应用材质颜色，并渲染成体素模型。" },
      note: "核心点：链上储存函数种子、系数、参数、调色板和验证哈希。用户看到的 3D 模型由代码重建，而不是下载 3D 文件。",
    },
    pipeline: { aria: "NCFM 验证流程", eyebrow: "链上验证流程", title: "客户端和合约可以共同认可什么。", body: "NCFM 通过把复杂视觉重建放到确定性的客户端运算里，保持链上载荷足够小。关键是所有客户端都能从同一段代码推出同一个模型哈希。", read: { title: "读取", body: "通过 RPC 从 PDA 或资产账户读取载荷。" }, decode: { title: "解码", body: "解析种子、调色板、傅里叶系数、场参数和验证哈希。" }, sample: { title: "采样", body: "在约定体素网格上运行 canonical 采样器。" }, render: { title: "渲染", body: "本地构建网格或体素实例缓冲，并对比确定性模型哈希。" } },
    meaning: { eyebrow: "技术意义", title: "为什么这对开放链游重要。", body: "目标不只是压缩，而是让游戏资产透明、永久、低成本读取，并且任何客户端或浏览器都能复现，不需要相信私有资产服务器。", permanent: { title: "永久", body: "只要载荷留在链上，资产定义就会随账户历史持续可用。" }, open: { title: "公开", body: "玩家可以检查重建物品所使用的函数代码和参数。" }, fast: { title: "高速", body: "一次短 RPC 读取可以替代多次元数据、网关和文件请求。" }, portable: { title: "可迁移", body: "同一段紧凑记录可以被游戏、浏览器、锻造工具和未来客户端解释。" } },
    spec: { aria: "NCFM 技术草图", model: { eyebrow: "数据模型", title: "一段拥有确定语义的极短文本。", item1: "头部：版本、物品类型、网格大小、量化方式。", item2: "函数：傅里叶描述符、有符号距离段、谐波厚度场。", item3: "调色板：紧凑材质 ID 和派生颜色规则。", item4: "验证器：由 canonical 采样生成的模型哈希。" }, cost: { eyebrow: "为什么重要", title: "链上 3D 会变成代码问题，而不是文件托管问题。", body: "如果物品可以被短函数描述，链上只需要保存最小种子和参数。世界仍然能渲染丰富 3D 资产，同时保持储存成本可预测、公开可审计。", link: "查看旧版傅里叶体素演示" } },
  },
  "zh-Hant": {
    meta: { title: "NCFM | 傅立葉鏈上 3D 資產", description: "NCFM 用來解釋 NiceChunk 如何把 3D 遊戲物品壓縮為鏈上可讀的傅立葉/函數程式碼，而不是依賴外部 3D 資產檔或 IPFS 元資料。" },
    nav: { aria: "主導覽" },
    hero: { eyebrow: "NICECHUNK 傅立葉模型", title: "3D 遊戲物品可以是鏈上可讀函數，而不是資產檔案。", body: "NCFM 是 NiceChunk 下一代資產層的研究方向：把極短的傅立葉/函數描述儲存在鏈上，客戶端透過 RPC 讀取後確定性還原體素物品。不需要 GLB 檔案，不需要可變 JSON，也不依賴 IPFS 閘道。", ctaLab: "開啟函數實驗室", ctaCompare: "比較儲存方式", ctaNcm: "返回 NCM", proofAria: "NCFM 保證", proof1: "確定性重建", proof2: "極短鏈上載荷", proof3: "不依賴外部資產託管" },
    payload: { aria: "NCFM 緊湊載荷", label: "鏈上載荷範例", meshFiles: "模型檔", ipfsLinks: "IPFS 連結", rpcRead: "RPC 讀取" },
    thesis: { aria: "儲存理念", asset: { title: "傳統遊戲資產", body: "錢包或 NFT 指向元資料，元資料再指向檔案，而檔案必須在鏈外某個位置持續可用。" }, ipfs: { title: "IPFS 式永久性", body: "它比普通伺服器更好，但遊戲仍然依賴外部內容路由、固定、閘道和元資料約定。" }, ncfm: { title: "NCFM 函數資產", body: "物品是一段確定性的函數載荷。所有權、渲染規則、驗證雜湊和視覺身份可以一起存在帳戶資料裡。" } },
    principle: { eyebrow: "原理圖", title: "儲存方程，重建物品。", body: "NCFM 把 3D 物品視為確定性的場，而不是靜態檔案。鏈上只保存最小 canonical 記錄：種子、量化係數、調色板規則、網格邊界和驗證雜湊。瀏覽器再把這段記錄展開成可見物品。", diagramAria: "NCFM 從方程到體素的流程", source: { title: "鏈上載荷" }, function: { title: "Canonical 函數" }, sampler: { title: "確定性採樣器" }, output: { title: "可渲染物品" }, cards: { formula: { kicker: "公式", title: "形狀就是一個場接受規則。", body: "對每個座標，客戶端都問同一個問題：這個點是否滿足約定函數？被接受的座標才會成為材質體素。" }, hash: { kicker: "雜湊", title: "使用者看到的模型可以被驗證。", body: "採樣順序、網格邊界、量化方式和調色板都是 canonical 的，因此生成的體素集合可以得到穩定模型雜湊。" }, chain: { kicker: "鏈上", title: "鏈上儲存身份，而不是大體積幾何。", body: "帳戶不需要攜帶沉重 mesh，只需要保存能永久重建和驗證物品的必要記錄。" } } },
    lab: { eyebrow: "函數相交實驗室", title: "由兩個緊湊函數生成的 3D 物品。", body: "這裡用鎬子演示，因為形狀容易理解：XY 函數定義輪廓、材質分區和顏色；Z 函數定義厚度。只有同時被兩個函數接受的座標才會成為體素。", voxelCount: "體素", copy: "複製載荷", visualLabel: "即時重建", pause: "暫停", resume: "繼續", terms: "傅立葉項", depth: "Z 厚度", canvasAria: "NCFM 傅立葉體素重建預覽", copied: "已複製", importVox: "導入 VOX", defaultModel: "正在使用函數生成的鎬子。", importedPrefix: "已導入 VOX", importFailed: "VOX 導入失敗", phases: ["傅立葉曲線", "XY 場", "Z 厚度", "體素輸出"] },
    stage: {
      xy: { title: "FXY：XY 平面上的傅立葉線條繪製", body: "第一步只看二維函數。傅立葉描述符把鎬子的輪廓還原成隨時間繪製的曲線，證明形狀可以由係數表達，而不是依賴圖片或模型檔案。" },
      intersection: { title: "FXY × FZ：XY 場與 Z 厚度場相交", body: "第二個函數把二維輪廓變成體積。藍色表示 XY 投影，金色表示 Z 軸厚度規則，綠色表示兩個函數同時接受的座標。" },
      voxel: { title: "相交結果：最終 3D 體素鎬子", body: "最終物品不是從 mesh 讀取。客戶端掃描確定性座標，只保留同時滿足兩個函數的位置，套用材質顏色，並渲染成體素模型。" },
      note: "核心點：鏈上儲存函數種子、係數、參數、調色板和驗證雜湊。使用者看到的 3D 模型由程式碼重建，而不是下載 3D 檔案。",
    },
    pipeline: { aria: "NCFM 驗證流程", eyebrow: "鏈上驗證流程", title: "客戶端和合約可以共同認可什麼。", body: "NCFM 透過把複雜視覺重建放到確定性的客戶端運算裡，保持鏈上載荷足夠小。關鍵是所有客戶端都能從同一段程式碼推出同一個模型雜湊。", read: { title: "讀取", body: "透過 RPC 從 PDA 或資產帳戶讀取載荷。" }, decode: { title: "解碼", body: "解析種子、調色板、傅立葉係數、場參數和驗證雜湊。" }, sample: { title: "採樣", body: "在約定體素網格上執行 canonical 採樣器。" }, render: { title: "渲染", body: "本地建構網格或體素實例緩衝，並比對確定性模型雜湊。" } },
    meaning: { eyebrow: "技術意義", title: "為什麼這對開放鏈遊重要。", body: "目標不只是壓縮，而是讓遊戲資產透明、永久、低成本讀取，並且任何客戶端或瀏覽器都能復現，不需要相信私有資產伺服器。", permanent: { title: "永久", body: "只要載荷留在鏈上，資產定義就會隨帳戶歷史持續可用。" }, open: { title: "公開", body: "玩家可以檢查重建物品所使用的函數程式碼和參數。" }, fast: { title: "高速", body: "一次短 RPC 讀取可以替代多次元資料、閘道和檔案請求。" }, portable: { title: "可遷移", body: "同一段緊湊記錄可以被遊戲、瀏覽器、鍛造工具和未來客戶端解釋。" } },
    spec: { aria: "NCFM 技術草圖", model: { eyebrow: "資料模型", title: "一段擁有確定語義的極短文字。", item1: "頭部：版本、物品類型、網格大小、量化方式。", item2: "函數：傅立葉描述符、有符號距離段、諧波厚度場。", item3: "調色板：緊湊材質 ID 和派生顏色規則。", item4: "驗證器：由 canonical 採樣生成的模型雜湊。" }, cost: { eyebrow: "為什麼重要", title: "鏈上 3D 會變成程式碼問題，而不是檔案託管問題。", body: "如果物品可以被短函數描述，鏈上只需要保存最小種子和參數。世界仍然能渲染豐富 3D 資產，同時保持儲存成本可預測、公開可審計。", link: "查看舊版傅立葉體素演示" } },
  },
  es: {
    meta: { title: "NCFM | Activos 3D Fourier en cadena", description: "NCFM explica como NiceChunk almacena objetos 3D de juego como codigo Fourier/funcional compacto directamente en cadena, sin depender de archivos 3D externos ni metadatos IPFS." },
    nav: { aria: "Navegacion principal" },
    hero: { eyebrow: "MODELO FOURIER NICECHUNK", title: "Objetos 3D como funciones legibles en cadena, no archivos de assets.", body: "NCFM es la direccion de investigacion para la siguiente capa de assets de NiceChunk: guardar una descripcion Fourier/funcional muy pequena en cadena y reconstruir el objeto voxel de forma determinista por RPC. Sin GLB, sin JSON mutable, sin depender de gateways IPFS.", ctaLab: "Abrir laboratorio", ctaCompare: "Comparar almacenamiento", ctaNcm: "Volver a NCM" },
    payload: { aria: "Payload compacto NCFM", label: "Ejemplo de payload en cadena", meshFiles: "archivos mesh", ipfsLinks: "enlaces IPFS", rpcRead: "lectura RPC" },
    thesis: { aria: "Tesis de almacenamiento", asset: { title: "Asset de juego tradicional", body: "Una wallet o NFT apunta a metadatos, los metadatos apuntan a un archivo, y ese archivo debe seguir disponible fuera de la cadena." }, ipfs: { title: "Permanencia estilo IPFS", body: "Es mejor que un servidor normal, pero el juego aun depende de enrutamiento externo, pinning, gateways y convenciones de metadatos." }, ncfm: { title: "Asset funcional NCFM", body: "El objeto es un payload funcional determinista. Propiedad, reglas de render, hash de verificacion e identidad visual pueden vivir juntos en los datos de cuenta." } },
    lab: { eyebrow: "LABORATORIO DE INTERSECCION", title: "Un objeto 3D generado por dos funciones compactas.", body: "Esta demo usa un pico porque la forma es facil de leer: una funcion XY define contorno, bandas de material y color; una funcion Z define grosor. Solo las coordenadas aceptadas por ambas funciones se convierten en voxels.", voxelCount: "Voxels", copy: "Copiar payload", visualLabel: "Reconstruccion en vivo", pause: "Pausar", resume: "Continuar", terms: "Terminos Fourier", depth: "Grosor Z", canvasAria: "Vista previa de reconstruccion voxel Fourier NCFM", copied: "Copiado", phases: ["Curva Fourier", "Campo XY", "Grosor Z", "Salida voxel"] },
    pipeline: { aria: "Pipeline de verificacion NCFM", eyebrow: "PIPELINE DE VERIFICACION EN CADENA", title: "Lo que cliente y contrato pueden acordar.", body: "NCFM mantiene pequeno el payload en cadena moviendo la reconstruccion visual pesada a una operacion determinista del cliente. Lo importante es que todos los clientes deriven el mismo hash de modelo desde el mismo codigo.", read: { title: "Leer", body: "Obtener el payload desde un PDA o cuenta de asset por RPC." }, decode: { title: "Decodificar", body: "Parsear seed, paleta, coeficientes Fourier, parametros de campo y hash verificador." }, sample: { title: "Muestrear", body: "Ejecutar el sampler canonico sobre la cuadricula voxel acordada." }, render: { title: "Renderizar", body: "Construir localmente un mesh o buffer de instancias voxel y comparar el hash determinista." } },
    spec: { aria: "Boceto tecnico NCFM", model: { eyebrow: "MODELO DE DATOS", title: "Un texto minimo con significado determinista.", item1: "Cabecera: version, clase de objeto, tamano de grid y cuantizacion.", item2: "Funciones: descriptores Fourier, segmentos de distancia con signo y campos armonicos de grosor.", item3: "Paleta: IDs compactos de material y reglas de color derivadas.", item4: "Verificador: hash de modelo generado por muestreo canonico." }, cost: { eyebrow: "POR QUE IMPORTA", title: "El 3D on-chain se vuelve un problema de codigo, no de hosting de archivos.", body: "Si el objeto puede describirse con una funcion corta, la cadena solo almacena la semilla y parametros minimos. El mundo puede renderizar assets 3D ricos manteniendo coste predecible y auditoria publica.", link: "Ver demo Fourier voxel anterior" } },
  },
  fr: {
    meta: { title: "NCFM | Assets 3D Fourier on-chain", description: "NCFM explique comment NiceChunk stocke des objets 3D de jeu sous forme de code Fourier/fonctionnel compact directement on-chain, sans fichiers 3D externes ni metadonnees IPFS." },
    nav: { aria: "Navigation principale" },
    hero: { eyebrow: "MODELE FOURIER NICECHUNK", title: "Des objets 3D sous forme de fonctions lisibles on-chain, pas de fichiers d'assets.", body: "NCFM explore la prochaine couche d'assets NiceChunk: stocker une courte description Fourier/fonctionnelle on-chain, puis reconstruire deterministiquement l'objet voxel par RPC. Pas de GLB, pas de JSON mutable, pas de dependance a une passerelle IPFS.", ctaLab: "Ouvrir le lab", ctaCompare: "Comparer le stockage", ctaNcm: "Retour NCM" },
    payload: { aria: "Payload compact NCFM", label: "Exemple de payload on-chain", meshFiles: "fichiers mesh", ipfsLinks: "liens IPFS", rpcRead: "lecture RPC" },
    thesis: { aria: "These de stockage", asset: { title: "Asset de jeu traditionnel", body: "Un wallet ou NFT pointe vers des metadonnees, les metadonnees pointent vers un fichier, et ce fichier doit rester disponible hors chaine." }, ipfs: { title: "Permanence style IPFS", body: "C'est mieux qu'un serveur classique, mais le jeu depend encore du routage externe, du pinning, des passerelles et des conventions de metadonnees." }, ncfm: { title: "Asset fonctionnel NCFM", body: "L'objet est un payload fonctionnel deterministe. Propriete, regles de rendu, hash de verification et identite visuelle peuvent vivre ensemble dans les donnees de compte." } },
    lab: { eyebrow: "LAB D'INTERSECTION DE FONCTIONS", title: "Un objet 3D genere par deux fonctions compactes.", body: "Cette demo utilise une pioche car la forme est facile a lire: une fonction XY definit le contour, les bandes de materiau et la couleur; une fonction Z definit l'epaisseur. Seules les coordonnees acceptees par les deux fonctions deviennent des voxels.", voxelCount: "Voxels", copy: "Copier payload", visualLabel: "Reconstruction live", pause: "Pause", resume: "Reprendre", terms: "Termes Fourier", depth: "Epaisseur Z", canvasAria: "Apercu de reconstruction voxel Fourier NCFM", copied: "Copie", phases: ["Courbe Fourier", "Champ XY", "Epaisseur Z", "Sortie voxel"] },
    pipeline: { aria: "Pipeline de verification NCFM", eyebrow: "PIPELINE DE VERIFICATION ON-CHAIN", title: "Ce que le client et le contrat peuvent partager.", body: "NCFM garde le payload on-chain petit en faisant de la reconstruction visuelle lourde une operation deterministe cote client. L'essentiel est que tous les clients derivent le meme hash de modele depuis le meme code.", read: { title: "Lire", body: "Recuperer le payload depuis un PDA ou un compte d'asset via RPC." }, decode: { title: "Decoder", body: "Parser seed, palette, coefficients Fourier, parametres de champ et hash verificateur." }, sample: { title: "Echantillonner", body: "Executer le sampler canonique sur la grille voxel convenue." }, render: { title: "Rendre", body: "Construire localement un mesh ou buffer d'instances voxel et comparer le hash deterministe." } },
    spec: { aria: "Croquis technique NCFM", model: { eyebrow: "MODELE DE DONNEES", title: "Un tres court texte au sens deterministe.", item1: "En-tete: version, classe d'objet, taille de grille, quantification.", item2: "Fonctions: descripteurs Fourier, segments de distance signee, champs harmoniques d'epaisseur.", item3: "Palette: IDs de materiau compacts et regles de couleur derivees.", item4: "Verificateur: hash de modele produit par echantillonnage canonique." }, cost: { eyebrow: "POURQUOI C'EST IMPORTANT", title: "Le 3D on-chain devient un probleme de code, pas d'hebergement de fichiers.", body: "Si l'objet peut etre decrit par une fonction courte, la chaine ne stocke que la seed et les parametres minimaux. Le monde peut encore rendre des assets 3D riches avec un cout previsible et une auditabilite publique.", link: "Voir l'ancienne demo Fourier voxel" } },
  },
  de: {
    meta: { title: "NCFM | Fourier-3D-Assets on-chain", description: "NCFM erklaert, wie NiceChunk 3D-Spielobjekte als kompakten Fourier/Funktionscode direkt on-chain speichert, statt externe 3D-Dateien oder IPFS-Metadaten zu benoetigen." },
    nav: { aria: "Hauptnavigation" },
    hero: { eyebrow: "NICECHUNK FOURIER MODELL", title: "3D-Spielobjekte als on-chain lesbare Funktionen, nicht als Asset-Dateien.", body: "NCFM ist die Forschungsrichtung fuer NiceChunks naechste Asset-Schicht: eine winzige Fourier/Funktionsbeschreibung on-chain speichern und das Voxel-Item deterministisch per RPC rekonstruieren. Keine GLB-Datei, kein veraenderbares JSON, keine IPFS-Gateway-Abhaengigkeit.", ctaLab: "Funktionslabor", ctaCompare: "Speicher vergleichen", ctaNcm: "Zurueck zu NCM" },
    payload: { aria: "Kompakter NCFM-Payload", label: "Beispiel-Payload on-chain", meshFiles: "Mesh-Dateien", ipfsLinks: "IPFS-Links", rpcRead: "RPC-Lesezugriff" },
    thesis: { aria: "Speicherthese", asset: { title: "Traditionelles Game-Asset", body: "Wallet oder NFT zeigen auf Metadaten, die Metadaten zeigen auf eine Datei, und diese Datei muss ausserhalb der Chain verfuegbar bleiben." }, ipfs: { title: "IPFS-artige Permanenz", body: "Besser als ein normaler Server, aber das Spiel haengt weiter von externem Routing, Pinning, Gateways und Metadaten-Konventionen ab." }, ncfm: { title: "NCFM-Funktionsasset", body: "Das Objekt ist ein deterministischer Funktions-Payload. Besitz, Rendering-Regeln, Verifizierungs-Hash und visuelle Identitaet koennen gemeinsam in Account-Daten liegen." } },
    lab: { eyebrow: "FUNKTIONS-INTERSEKTIONSLABOR", title: "Ein 3D-Item aus zwei kompakten Funktionen.", body: "Diese Demo nutzt eine Spitzhacke, weil die Form klar lesbar ist: Eine XY-Funktion definiert Umriss, Materialbaender und Farbe; eine Z-Funktion definiert Dicke. Nur Koordinaten, die beide Funktionen akzeptieren, werden zu Voxeln.", voxelCount: "Voxel", copy: "Payload kopieren", visualLabel: "Live-Rekonstruktion", pause: "Pause", resume: "Weiter", terms: "Fourier-Terme", depth: "Z-Dicke", canvasAria: "NCFM Fourier-Voxel-Rekonstruktionsvorschau", copied: "Kopiert", phases: ["Fourier-Kurve", "XY-Feld", "Z-Dicke", "Voxel-Ausgabe"] },
    pipeline: { aria: "NCFM-Verifizierungspipeline", eyebrow: "ON-CHAIN-VERIFIZIERUNG", title: "Worauf Client und Contract sich einigen koennen.", body: "NCFM haelt den Chain-Payload klein, indem die schwere visuelle Rekonstruktion eine deterministische Client-Operation ist. Entscheidend ist, dass alle Clients aus demselben Code denselben Modell-Hash ableiten.", read: { title: "Lesen", body: "Payload per RPC aus einem PDA oder Asset-Account abrufen." }, decode: { title: "Dekodieren", body: "Seed, Palette, Fourier-Koeffizienten, Feldparameter und Verifizierungs-Hash parsen." }, sample: { title: "Sampeln", body: "Den kanonischen Sampler ueber dem vereinbarten Voxel-Raster ausfuehren." }, render: { title: "Rendern", body: "Lokal Mesh oder Voxel-Instanzbuffer bauen und den deterministischen Modell-Hash vergleichen." } },
    spec: { aria: "Technische NCFM-Skizze", model: { eyebrow: "DATENMODELL", title: "Ein winziger Textdatensatz mit deterministischer Bedeutung.", item1: "Header: Version, Item-Klasse, Rastergroesse, Quantisierung.", item2: "Funktionen: Fourier-Deskriptoren, signierte Distanzsegmente, harmonische Dickenfelder.", item3: "Palette: kompakte Material-IDs und abgeleitete Farbregeln.", item4: "Verifier: Modell-Hash aus kanonischem Sampling." }, cost: { eyebrow: "WARUM ES WICHTIG IST", title: "On-chain 3D wird ein Codeproblem, kein Datei-Hosting-Problem.", body: "Wenn ein Item durch eine kurze Funktion beschrieben werden kann, speichert die Chain nur minimale Seeds und Parameter. Die Welt kann weiterhin reichhaltige 3D-Assets rendern, mit planbaren Speicherkosten und oeffentlicher Pruefbarkeit.", link: "Aeltere Fourier-Voxel-Demo ansehen" } },
  },
  ja: {
    meta: { title: "NCFM | Fourier オンチェーン 3D アセット", description: "NCFM は、NiceChunk が外部 3D ファイルや IPFS メタデータに頼らず、3D ゲームアイテムをコンパクトな Fourier/関数コードとして直接オンチェーン保存する考え方を説明します。" },
    nav: { aria: "メインナビゲーション" },
    hero: { eyebrow: "NICECHUNK FOURIER MODEL", title: "3Dゲームアイテムを資産ファイルではなく、チェーンで読める関数として表現する。", body: "NCFM は NiceChunk の次世代アセット層に向けた研究です。短い Fourier/関数記述をオンチェーンに保存し、クライアントが RPC で読み取り、決定論的にボクセルアイテムを復元します。GLB も可変 JSON も IPFS ゲートウェイ依存も不要です。", ctaLab: "ラボを開く", ctaCompare: "保存方式を比較", ctaNcm: "NCM に戻る" },
    payload: { aria: "NCFM コンパクトペイロード", label: "チェーン上ペイロード例", meshFiles: "メッシュファイル", ipfsLinks: "IPFS リンク", rpcRead: "RPC 読み取り" },
    thesis: { aria: "保存思想", asset: { title: "従来のゲームアセット", body: "ウォレットや NFT がメタデータを指し、メタデータがファイルを指します。そのファイルはチェーン外で継続的に利用可能である必要があります。" }, ipfs: { title: "IPFS 型の永続性", body: "通常サーバーより良い方式ですが、ゲームは依然として外部ルーティング、ピン留め、ゲートウェイ、メタデータ規約に依存します。" }, ncfm: { title: "NCFM 関数アセット", body: "アイテムは決定論的な関数ペイロードです。所有権、レンダリング規則、検証ハッシュ、視覚的アイデンティティをアカウントデータ内にまとめられます。" } },
    lab: { eyebrow: "関数交差ラボ", title: "2つのコンパクトな関数から生成される 3D アイテム。", body: "このデモでは形を読み取りやすいツルハシを使います。XY 関数が輪郭、素材帯、色を定義し、Z 関数が厚みを定義します。両方の関数に受け入れられた座標だけがボクセルになります。", voxelCount: "ボクセル", copy: "ペイロードをコピー", visualLabel: "ライブ再構築", pause: "一時停止", resume: "再開", terms: "Fourier 項", depth: "Z 厚み", canvasAria: "NCFM Fourier ボクセル再構築プレビュー", copied: "コピー済み", phases: ["Fourier 曲線", "XY フィールド", "Z 厚み", "ボクセル出力"] },
    pipeline: { aria: "NCFM 検証パイプライン", eyebrow: "オンチェーン検証パイプライン", title: "クライアントとコントラクトが合意できるもの。", body: "NCFM は重い視覚再構築を決定論的なクライアント処理にすることで、チェーン上ペイロードを小さく保ちます。重要なのは、すべてのクライアントが同じコードから同じモデルハッシュを導けることです。", read: { title: "読み取り", body: "RPC で PDA またはアセットアカウントからペイロードを取得します。" }, decode: { title: "デコード", body: "シード、パレット、Fourier 係数、フィールドパラメータ、検証ハッシュを解析します。" }, sample: { title: "サンプル", body: "合意されたボクセルグリッド上で canonical サンプラーを実行します。" }, render: { title: "レンダー", body: "ローカルでメッシュまたはボクセルインスタンスバッファを構築し、決定論的モデルハッシュを比較します。" } },
    spec: { aria: "NCFM 技術スケッチ", model: { eyebrow: "データモデル", title: "決定論的な意味を持つ短いテキスト記録。", item1: "ヘッダー: バージョン、アイテムクラス、グリッドサイズ、量子化。", item2: "関数: Fourier 記述子、符号付き距離セグメント、調和厚みフィールド。", item3: "パレット: コンパクトな素材 ID と派生カラー規則。", item4: "検証器: canonical サンプリングで生成されるモデルハッシュ。" }, cost: { eyebrow: "なぜ重要か", title: "オンチェーン 3D はファイルホスティングではなくコードの問題になる。", body: "アイテムを短い関数で記述できれば、チェーンは最小限のシードとパラメータだけを保存します。世界は豊かな 3D アセットを描画しながら、保存コストを予測可能で公開監査可能にできます。", link: "旧 Fourier ボクセルデモを見る" } },
  },
  ru: {
    meta: { title: "NCFM | Fourier 3D-ассеты on-chain", description: "NCFM объясняет, как NiceChunk хранит 3D-предметы игры как компактный Fourier/функциональный код прямо on-chain, без внешних 3D-файлов и IPFS-метаданных." },
    nav: { aria: "Основная навигация" },
    hero: { eyebrow: "FOURIER-МОДЕЛЬ NICECHUNK", title: "3D-предметы как читаемые on-chain функции, а не файлы ассетов.", body: "NCFM исследует следующий слой ассетов NiceChunk: короткое Fourier/функциональное описание хранится on-chain, а клиент детерминированно восстанавливает voxel-предмет через RPC. Без GLB, изменяемого JSON и зависимости от IPFS-шлюза.", ctaLab: "Открыть лабораторию", ctaCompare: "Сравнить хранение", ctaNcm: "Назад к NCM" },
    payload: { aria: "Компактный payload NCFM", label: "Пример on-chain payload", meshFiles: "mesh-файлы", ipfsLinks: "IPFS-ссылки", rpcRead: "RPC-чтение" },
    thesis: { aria: "Тезис хранения", asset: { title: "Традиционный игровой ассет", body: "Кошелек или NFT указывает на метаданные, метаданные указывают на файл, а файл должен оставаться доступным вне сети." }, ipfs: { title: "Постоянство в стиле IPFS", body: "Это лучше обычного сервера, но игра все еще зависит от внешней маршрутизации, pinning, шлюзов и соглашений метаданных." }, ncfm: { title: "Функциональный ассет NCFM", body: "Предмет является детерминированным функциональным payload. Владение, правила рендера, проверочный хэш и визуальная идентичность могут жить вместе в данных аккаунта." } },
    lab: { eyebrow: "ЛАБОРАТОРИЯ ПЕРЕСЕЧЕНИЯ ФУНКЦИЙ", title: "3D-предмет, созданный двумя компактными функциями.", body: "В демо используется кирка, потому что форму легко читать: XY-функция задает контур, материалы и цвет; Z-функция задает толщину. Только координаты, принятые обеими функциями, становятся voxels.", voxelCount: "Voxels", copy: "Копировать payload", visualLabel: "Живая реконструкция", pause: "Пауза", resume: "Продолжить", terms: "Fourier-члены", depth: "Толщина Z", canvasAria: "Превью реконструкции NCFM Fourier voxel", copied: "Скопировано", phases: ["Кривая Fourier", "Поле XY", "Толщина Z", "Voxel-вывод"] },
    pipeline: { aria: "Pipeline проверки NCFM", eyebrow: "ON-CHAIN PIPELINE ПРОВЕРКИ", title: "С чем могут согласиться клиент и контракт.", body: "NCFM держит on-chain payload маленьким, делая тяжелую визуальную реконструкцию детерминированной операцией клиента. Главное, что все клиенты получают один и тот же хэш модели из одного кода.", read: { title: "Чтение", body: "Получить payload из PDA или asset-аккаунта через RPC." }, decode: { title: "Декод", body: "Разобрать seed, палитру, Fourier-коэффициенты, параметры поля и проверочный хэш." }, sample: { title: "Сэмпл", body: "Запустить canonical sampler по согласованной voxel-сетке." }, render: { title: "Рендер", body: "Локально построить mesh или voxel instance buffer и сравнить детерминированный хэш модели." } },
    spec: { aria: "Технический эскиз NCFM", model: { eyebrow: "МОДЕЛЬ ДАННЫХ", title: "Короткая текстовая запись с детерминированным смыслом.", item1: "Заголовок: версия, класс предмета, размер сетки, квантование.", item2: "Функции: Fourier-дескрипторы, signed-distance сегменты, гармонические поля толщины.", item3: "Палитра: компактные material ID и производные правила цвета.", item4: "Verifier: хэш модели, созданный canonical sampling." }, cost: { eyebrow: "ПОЧЕМУ ЭТО ВАЖНО", title: "On-chain 3D становится задачей кода, а не файлового хостинга.", body: "Если предмет описывается короткой функцией, сеть хранит только минимальный seed и параметры. Мир может рендерить богатые 3D-ассеты, сохраняя предсказуемую стоимость хранения и публичную проверяемость.", link: "Смотреть старое Fourier voxel демо" } },
  },
  ko: {
    meta: { title: "NCFM | Fourier 온체인 3D 자산", description: "NCFM은 NiceChunk가 외부 3D 파일이나 IPFS 메타데이터 없이 3D 게임 아이템을 압축된 Fourier/함수 코드로 온체인에 직접 저장하는 방식을 설명합니다." },
    nav: { aria: "기본 탐색" },
    hero: { eyebrow: "NICECHUNK FOURIER MODEL", title: "3D 게임 아이템을 자산 파일이 아니라 체인에서 읽는 함수로 표현합니다.", body: "NCFM은 NiceChunk의 다음 자산 레이어 연구입니다. 짧은 Fourier/함수 설명을 온체인에 저장하고, 클라이언트가 RPC로 읽어 결정적으로 복셀 아이템을 재구성합니다. GLB, 변경 가능한 JSON, IPFS 게이트웨이에 의존하지 않습니다.", ctaLab: "함수 랩 열기", ctaCompare: "저장 비교", ctaNcm: "NCM으로 돌아가기" },
    payload: { aria: "NCFM 압축 페이로드", label: "온체인 페이로드 예시", meshFiles: "메시 파일", ipfsLinks: "IPFS 링크", rpcRead: "RPC 읽기" },
    thesis: { aria: "저장 철학", asset: { title: "기존 게임 자산", body: "지갑이나 NFT가 메타데이터를 가리키고, 메타데이터가 파일을 가리키며, 그 파일은 체인 밖 어딘가에서 계속 사용 가능해야 합니다." }, ipfs: { title: "IPFS식 영속성", body: "일반 서버보다 낫지만 게임은 여전히 외부 라우팅, 핀ning, 게이트웨이, 메타데이터 규약에 의존합니다." }, ncfm: { title: "NCFM 함수 자산", body: "아이템은 결정론적 함수 페이로드입니다. 소유권, 렌더 규칙, 검증 해시, 시각적 정체성을 계정 데이터 안에 함께 둘 수 있습니다." } },
    lab: { eyebrow: "함수 교차 랩", title: "두 개의 압축 함수로 생성되는 3D 아이템.", body: "이 데모는 형태를 읽기 쉬운 곡괭이를 사용합니다. XY 함수는 윤곽, 재질 구간, 색상을 정의하고 Z 함수는 두께를 정의합니다. 두 함수가 모두 허용한 좌표만 복셀이 됩니다.", voxelCount: "복셀", copy: "페이로드 복사", visualLabel: "실시간 재구성", pause: "일시정지", resume: "계속", terms: "Fourier 항", depth: "Z 두께", canvasAria: "NCFM Fourier 복셀 재구성 미리보기", copied: "복사됨", phases: ["Fourier 곡선", "XY 필드", "Z 두께", "복셀 출력"] },
    pipeline: { aria: "NCFM 검증 파이프라인", eyebrow: "온체인 검증 파이프라인", title: "클라이언트와 컨트랙트가 합의할 수 있는 것.", body: "NCFM은 무거운 시각 재구성을 결정론적 클라이언트 연산으로 만들어 온체인 페이로드를 작게 유지합니다. 핵심은 모든 클라이언트가 같은 코드에서 같은 모델 해시를 도출하는 것입니다.", read: { title: "읽기", body: "RPC로 PDA 또는 자산 계정에서 페이로드를 가져옵니다." }, decode: { title: "디코드", body: "시드, 팔레트, Fourier 계수, 필드 파라미터, 검증 해시를 파싱합니다." }, sample: { title: "샘플링", body: "합의된 복셀 그리드에서 canonical 샘플러를 실행합니다." }, render: { title: "렌더", body: "로컬에서 메시 또는 복셀 인스턴스 버퍼를 만들고 결정론적 모델 해시를 비교합니다." } },
    spec: { aria: "NCFM 기술 스케치", model: { eyebrow: "데이터 모델", title: "결정론적 의미를 가진 짧은 텍스트 기록.", item1: "헤더: 버전, 아이템 클래스, 그리드 크기, 양자화.", item2: "함수: Fourier 디스크립터, signed-distance 세그먼트, 조화 두께 필드.", item3: "팔레트: 압축 재질 ID와 파생 색상 규칙.", item4: "검증기: canonical 샘플링으로 생성된 모델 해시." }, cost: { eyebrow: "왜 중요한가", title: "온체인 3D는 파일 호스팅 문제가 아니라 코드 문제가 됩니다.", body: "아이템을 짧은 함수로 설명할 수 있다면 체인은 최소 시드와 파라미터만 저장합니다. 세계는 풍부한 3D 자산을 렌더링하면서도 저장 비용을 예측 가능하고 공개 검증 가능하게 유지할 수 있습니다.", link: "이전 Fourier 복셀 데모 보기" } },
  },
};

const canvases = {
  xy: document.querySelector("#canvas2d"),
  intersection: document.querySelector("#canvasIntersect"),
  voxel: document.querySelector("#canvas3d"),
};
const contexts = Object.fromEntries(Object.entries(canvases).map(([key, canvas]) => [key, canvas.getContext("2d")]));
const termsRange = document.querySelector("#termsRange");
const depthRange = document.querySelector("#depthRange");
const termsOut = document.querySelector("#termsOut");
const depthOut = document.querySelector("#depthOut");
const voxelCount = document.querySelector("#voxelCount");
const termBadge = document.querySelector("#termBadge");
const drawBadge = document.querySelector("#drawBadge");
const fieldBadge = document.querySelector("#fieldBadge");
const voxelBadge = document.querySelector("#voxelBadge");
const cycleBadge = document.querySelector("#cycleBadge");
const toggleMotion = document.querySelector("#toggleMotion");
const copyPayload = document.querySelector("#copyPayload");
const payloadCode = document.querySelector("#payloadCode");
const voxImport = document.querySelector("#voxImport");
const importStatus = document.querySelector("#importStatus");

let running = true;
let lastTime = performance.now();
let time = 0;
let coefficients = [];
let pathPoints = [];
let voxels = [];
let importedModel = null;

setSiteLoadingProgress(36);
await initI18n();
setSiteLoadingProgress(62);
applyLocalTranslations();
prepareFourier();
rebuildVoxels();
updatePayload();
setupEvents();
resizeCanvases();
finishSiteLoading();
requestAnimationFrame(tick);

function setupEvents() {
  window.addEventListener("resize", resizeCanvases, { passive: true });
  window.addEventListener("nicechunk:languagechange", applyLocalTranslations);
  termsRange.addEventListener("input", () => {
    termsOut.value = termsRange.value;
    updateBadges();
    updatePayload();
  });
  depthRange.addEventListener("input", () => {
    depthOut.value = depthRange.value;
    rebuildVoxels();
    updatePayload();
  });
  toggleMotion.addEventListener("click", () => {
    running = !running;
    toggleMotion.textContent = localText(running ? "lab.pause" : "lab.resume");
  });
  copyPayload.addEventListener("click", async () => {
    await navigator.clipboard?.writeText(payloadCode.textContent || "");
    const previous = copyPayload.textContent;
    copyPayload.textContent = localText("lab.copied");
    window.setTimeout(() => {
      copyPayload.textContent = previous;
    }, 1200);
  });
  voxImport.addEventListener("change", async () => {
    const file = voxImport.files?.[0];
    if (!file) return;
    await importVoxFile(file);
  });
}

function applyLocalTranslations() {
  document.querySelectorAll("[data-ncfm-i18n]").forEach((element) => {
    element.textContent = localText(element.dataset.ncfmI18n);
  });
  translateAttribute("data-ncfm-i18n-content", "content");
  translateAttribute("data-ncfm-i18n-aria-label", "aria-label");
  document.title = localText("meta.title");
  toggleMotion.textContent = localText(running ? "lab.pause" : "lab.resume");
  if (!importedModel) importStatus.textContent = localText("lab.defaultModel");
}

function translateAttribute(dataName, attributeName) {
  document.querySelectorAll(`[${dataName}]`).forEach((element) => {
    element.setAttribute(attributeName, localText(element.getAttribute(dataName)));
  });
}

function localText(path) {
  return getByPath(mergedDictionary(), path) ?? getByPath(fallbackCopy, path) ?? path;
}

function mergedDictionary() {
  const language = currentLanguage();
  return deepMerge(fallbackCopy, dictionaries[language] || {});
}

function deepMerge(base, extra) {
  if (!extra || typeof extra !== "object" || Array.isArray(extra)) return extra ?? base;
  const output = { ...base };
  Object.entries(extra).forEach(([key, value]) => {
    if (value && typeof value === "object" && !Array.isArray(value)) output[key] = deepMerge(base?.[key] || {}, value);
    else output[key] = value;
  });
  return output;
}

function getByPath(source, path) {
  return path.split(".").reduce((value, part) => (value && Object.hasOwn(value, part) ? value[part] : undefined), source);
}

async function importVoxFile(file) {
  try {
    importStatus.textContent = `${localText("lab.importedPrefix")}: ${file.name} ...`;
    const vox = parseVox(await file.arrayBuffer());
    const model = vox.models[0];
    if (!model || !model.voxels.length) throw new Error("Empty VOX model.");
    importedModel = normalizeVoxModel(model, file.name);
    pathPoints = importedModel.pathPoints;
    coefficients = computeDft(pathPoints);
    rebuildVoxels();
    updatePayload();
    importStatus.textContent = `${localText("lab.importedPrefix")}: ${file.name} · ${voxels.length} voxels`;
  } catch (error) {
    importedModel = null;
    prepareFourier();
    rebuildVoxels();
    updatePayload();
    importStatus.textContent = `${localText("lab.importFailed")}: ${error.message}`;
  }
}

function normalizeVoxModel(model, filename) {
  const maxSize = Math.max(model.size.x, model.size.y, model.size.z, 1);
  const scale = Math.max(1, Math.floor(38 / maxSize));
  const centerX = (model.size.x - 1) / 2;
  const centerDepth = (model.size.y - 1) / 2;
  const centerY = (model.size.z - 1) / 2;
  const normalized = [];
  model.voxels.forEach((voxel) => {
    const baseX = Math.round((voxel.x - centerX) * scale);
    const baseY = Math.round((voxel.z - centerY) * scale);
    const baseZ = Math.round((centerDepth - voxel.y) * scale);
    for (let dx = 0; dx < scale; dx += 1) {
      for (let dy = 0; dy < scale; dy += 1) {
        for (let dz = 0; dz < scale; dz += 1) {
          normalized.push({
            x: baseX + dx,
            y: baseY + dy,
            z: baseZ + dz,
            color: hexToRgb(voxel.color || "#ffffff"),
            material: "vox",
          });
        }
      }
    }
  });
  return {
    filename,
    voxels: normalized,
    pathPoints: buildSilhouettePath(normalized),
  };
}

function buildSilhouettePath(sourceVoxels) {
  const cells = new Set(sourceVoxels.map((voxel) => `${voxel.x},${voxel.y}`));
  const edge = [];
  cells.forEach((key) => {
    const [x, y] = key.split(",").map(Number);
    if (!cells.has(`${x + 1},${y}`) || !cells.has(`${x - 1},${y}`) || !cells.has(`${x},${y + 1}`) || !cells.has(`${x},${y - 1}`)) {
      edge.push([x, y]);
    }
  });
  if (edge.length < 6) return pathPoints.length ? pathPoints : [[-10, -10], [10, -10], [10, 10], [-10, 10], [-10, -10]];
  const center = edge.reduce((sum, point) => [sum[0] + point[0] / edge.length, sum[1] + point[1] / edge.length], [0, 0]);
  return edge
    .sort((a, b) => Math.atan2(a[1] - center[1], a[0] - center[0]) - Math.atan2(b[1] - center[1], b[0] - center[0]))
    .filter((_, index) => index % Math.max(1, Math.floor(edge.length / 180)) === 0);
}

function prepareFourier() {
  importedModel = null;
  const outline = [
    [-15, 8], [-9, 11], [-3, 10], [1, 8], [10, 12], [16, 10], [12, 6], [4, 5],
    [2, 3], [2, -25], [-2, -25], [-2, 3], [-7, 4], [-14, 5], [-17, 7], [-15, 8],
  ];
  pathPoints = samplePolyline(outline, 220);
  coefficients = computeDft(pathPoints);
}

function samplePolyline(points, count) {
  const segments = [];
  let total = 0;
  for (let index = 0; index < points.length - 1; index += 1) {
    const a = points[index];
    const b = points[index + 1];
    const length = Math.hypot(b[0] - a[0], b[1] - a[1]);
    segments.push({ a, b, length });
    total += length;
  }
  const samples = [];
  for (let i = 0; i < count; i += 1) {
    let cursor = (i / count) * total;
    const segment = segments.find((item) => {
      if (cursor <= item.length) return true;
      cursor -= item.length;
      return false;
    }) || segments[segments.length - 1];
    const t = segment.length ? cursor / segment.length : 0;
    samples.push([
      segment.a[0] + (segment.b[0] - segment.a[0]) * t,
      segment.a[1] + (segment.b[1] - segment.a[1]) * t,
    ]);
  }
  return samples;
}

function computeDft(points) {
  const count = points.length;
  const result = [];
  for (let k = -34; k <= 34; k += 1) {
    let re = 0;
    let im = 0;
    for (let n = 0; n < count; n += 1) {
      const angle = (-2 * Math.PI * k * n) / count;
      const x = points[n][0];
      const y = points[n][1];
      re += x * Math.cos(angle) - y * Math.sin(angle);
      im += x * Math.sin(angle) + y * Math.cos(angle);
    }
    result.push({ k, re: re / count, im: im / count, amp: Math.hypot(re, im) / count });
  }
  return result.sort((a, b) => b.amp - a.amp);
}

function evalFourier(t, terms) {
  let x = 0;
  let y = 0;
  coefficients.slice(0, terms).forEach((coefficient) => {
    const angle = 2 * Math.PI * coefficient.k * t;
    x += coefficient.re * Math.cos(angle) - coefficient.im * Math.sin(angle);
    y += coefficient.re * Math.sin(angle) + coefficient.im * Math.cos(angle);
  });
  return [x, y];
}

function rebuildVoxels() {
  if (importedModel) {
    voxels = importedModel.voxels.slice();
    voxelCount.textContent = String(voxels.length);
    updateBadges();
    return;
  }
  const depth = Number(depthRange.value);
  voxels = [];
  for (let y = -25; y <= 13; y += 1) {
    for (let x = -18; x <= 18; x += 1) {
      const xy = fxy(x, y);
      if (!xy.inside) continue;
      const localDepth = Math.max(1, Math.round(depth / 2 + Math.sin(x * 0.27 + y * 0.31) * 0.7));
      for (let z = -localDepth; z <= localDepth; z += 1) {
        if (fz(z, localDepth)) voxels.push({ x, y, z, color: xy.color, material: xy.material });
      }
    }
  }
  voxels.sort((a, b) => (a.x + a.y + a.z) - (b.x + b.y + b.z));
  voxelCount.textContent = String(voxels.length);
  updateBadges();
}

function fxy(x, y) {
  const handle = Math.abs(x) <= 2 && y >= -25 && y <= 4;
  const headCore = y >= 4 && y <= 11 && Math.abs(x) <= 17 - Math.abs(y - 8) * 1.5;
  const pickTip = (x > 9 && y >= 5 && y <= 10 && x + (y - 7) * 0.6 <= 17) || (x < -9 && y >= 5 && y <= 10 && -x - (y - 7) * 0.6 <= 17);
  const neck = Math.abs(x) <= 6 && y >= 2 && y <= 7;
  const inside = handle || headCore || pickTip || neck;
  const metal = y >= 4 || Math.abs(x) > 3;
  const shade = Math.sin(x * 0.67 + y * 0.29) * 10;
  return {
    inside,
    material: metal ? "metal" : "wood",
    color: metal ? rgb(154 + shade, 196 + shade, 214 + shade) : rgb(151 + shade, 96 + shade * 0.5, 50),
  };
}

function fz(z, localDepth) {
  return Math.cos((Math.PI * z) / Math.max(1, localDepth + 0.6)) > -0.4;
}

function rgb(r, g, b) {
  return `rgb(${Math.round(r)}, ${Math.round(g)}, ${Math.round(b)})`;
}

function hexToRgb(hex) {
  const value = String(hex || "#ffffff").replace("#", "");
  const numeric = Number.parseInt(value.length === 3 ? value.replace(/(.)/g, "$1$1") : value.slice(0, 6), 16);
  if (!Number.isFinite(numeric)) return "rgb(255, 255, 255)";
  return rgb((numeric >> 16) & 255, (numeric >> 8) & 255, numeric & 255);
}

function updatePayload() {
  const terms = Number(termsRange.value);
  const depth = Number(depthRange.value);
  const kind = importedModel ? "VOX" : "PKX";
  const hash = simpleHash(`${kind}:${terms}:${depth}:${voxels.length}:${importedModel?.filename || ""}`);
  payloadCode.textContent = `NCFM1.${kind}.S37x39x${depth}.FXY:${importedModel ? "voxproj" : `fd${terms}+seg`}.FZ:h${depth}.PAL:auto.H:${hash}`;
}

function updateBadges() {
  const terms = Number(termsRange.value);
  termsOut.value = String(terms);
  depthOut.value = depthRange.value;
  termBadge.textContent = `terms: ${terms} / 69`;
  fieldBadge.textContent = `intersection: ${voxels.length} voxels`;
}

function simpleHash(value) {
  let hash = 2166136261;
  for (let index = 0; index < value.length; index += 1) {
    hash ^= value.charCodeAt(index);
    hash = Math.imul(hash, 16777619);
  }
  return (hash >>> 0).toString(16).padStart(8, "0").slice(0, 8);
}

function resizeCanvases() {
  Object.values(canvases).forEach((canvas) => {
    const rect = canvas.getBoundingClientRect();
    const ratio = Math.min(window.devicePixelRatio || 1, 2);
    canvas.width = Math.max(1, Math.floor(rect.width * ratio));
    canvas.height = Math.max(1, Math.floor(rect.height * ratio));
    const context = canvas.getContext("2d");
    context.setTransform(ratio, 0, 0, ratio, 0, 0);
  });
}

function tick(now) {
  const delta = Math.min(50, now - lastTime) / 1000;
  lastTime = now;
  if (running) time += delta;
  drawAll();
  requestAnimationFrame(tick);
}

function drawAll() {
  drawFourierStage();
  drawIntersectionStage();
  drawVoxelStage();
}

function clearStage(key) {
  const canvas = canvases[key];
  const context = contexts[key];
  const width = canvas.clientWidth;
  const height = canvas.clientHeight;
  context.clearRect(0, 0, width, height);
  drawCanvasBackground(context, width, height);
  return { context, width, height };
}

function drawCanvasBackground(context, width, height) {
  const grid = 28;
  context.save();
  context.globalAlpha = 0.32;
  context.strokeStyle = "rgba(144, 215, 255, 0.08)";
  context.lineWidth = 1;
  for (let x = 0; x < width; x += grid) {
    context.beginPath();
    context.moveTo(x, 0);
    context.lineTo(x, height);
    context.stroke();
  }
  for (let y = 0; y < height; y += grid) {
    context.beginPath();
    context.moveTo(0, y);
    context.lineTo(width, y);
    context.stroke();
  }
  context.restore();
}

function drawFourierStage() {
  const { context, width, height } = clearStage("xy");
  const terms = Number(termsRange.value);
  const originX = width / 2;
  const originY = height / 2 + 16;
  const scale = Math.min(width / 48, height / 42);
  const progress = 0.5 + Math.sin(time * 0.55) * 0.5;
  const drawCount = Math.max(4, Math.floor(pathPoints.length * progress));
  drawBadge.textContent = `draw: ${Math.round(progress * 100)}%`;

  context.save();
  context.translate(originX, originY);
  context.strokeStyle = "rgba(144, 215, 255, 0.2)";
  context.lineWidth = 1;
  context.beginPath();
  context.moveTo(-width / 2 + 30, 0);
  context.lineTo(width / 2 - 30, 0);
  context.moveTo(0, -height / 2 + 30);
  context.lineTo(0, height / 2 - 30);
  context.stroke();

  context.lineWidth = 1.5;
  context.strokeStyle = "rgba(144, 215, 255, 0.24)";
  drawClosedPath(context, pathPoints, scale, pathPoints.length);
  context.stroke();

  const fourierPath = [];
  for (let i = 0; i < pathPoints.length; i += 1) fourierPath.push(evalFourier(i / pathPoints.length, terms));
  context.lineWidth = 3;
  context.strokeStyle = "#8cffce";
  context.shadowColor = "rgba(140, 255, 206, 0.58)";
  context.shadowBlur = 18;
  drawClosedPath(context, fourierPath, scale, drawCount);
  context.stroke();
  context.restore();
}

function drawClosedPath(context, points, scale, count) {
  context.beginPath();
  points.slice(0, count).forEach((point, index) => {
    const px = point[0] * scale;
    const py = -point[1] * scale;
    if (index === 0) context.moveTo(px, py);
    else context.lineTo(px, py);
  });
}

function drawIntersectionStage() {
  const { context, width, height } = clearStage("intersection");
  const angle = 0.82 + Math.sin(time * 0.32) * 0.14;
  const columns = getFieldColumns();
  const fit = fitVoxelProjection(columns.flatMap((column) => [
    { x: column.x, y: column.y, z: column.minZ },
    { x: column.x, y: column.y, z: column.maxZ },
  ]), angle, width, height, 34);
  const scale = fit.scale;
  const ox = fit.x;
  const oy = fit.y;
  const scan = (time * 0.38) % 1;
  const scanX = -18 + scan * 36;

  drawVoxelAxes(context, width, height, angle, scale, ox, oy);

  const planeCorners = [
    projectVoxelPoint(-19, -25, 0, angle, scale, ox, oy),
    projectVoxelPoint(19, -25, 0, angle, scale, ox, oy),
    projectVoxelPoint(19, 13, 0, angle, scale, ox, oy),
    projectVoxelPoint(-19, 13, 0, angle, scale, ox, oy),
  ];
  drawPolygon(context, planeCorners, "rgba(144, 215, 255, 0.055)", "rgba(144, 215, 255, 0.22)");

  const hitCubes = [];
  columns.forEach(({ x, y, minZ, maxZ, depth }) => {
    if (Math.abs(x - scanX) < 5.2 || ((x * 7 + y * 3 + Math.floor(time * 5)) % 17 === 0)) {
      const step = Math.max(1, Math.ceil((maxZ - minZ + 1) / 3));
      for (let z = minZ; z <= maxZ; z += step) {
        if (importedModel || fz(z, depth)) hitCubes.push({ x, y, z, color: "rgb(112, 255, 180)", material: "hit" });
      }
    }
  });

  columns.forEach(({ x, y, minZ, maxZ }) => {
    const point = projectVoxelPoint(x, y, 0, angle, scale, ox, oy);
    context.fillStyle = "rgba(144, 215, 255, 0.32)";
    context.beginPath();
    context.arc(point.x, point.y, Math.max(1.4, scale * 0.14), 0, Math.PI * 2);
    context.fill();

    if (Math.abs(x - scanX) > 6 && (x + y + Math.floor(time * 3)) % 5 !== 0) return;
    const a = projectVoxelPoint(x, y, minZ, angle, scale, ox, oy);
    const b = projectVoxelPoint(x, y, maxZ, angle, scale, ox, oy);
    const glow = Math.max(0.25, 1 - Math.abs(x - scanX) / 9);
    context.strokeStyle = `rgba(255, 224, 138, ${0.18 + glow * 0.52})`;
    context.lineWidth = 1 + glow * 1.4;
    context.beginPath();
    context.moveTo(a.x, a.y);
    context.lineTo(b.x, b.y);
    context.stroke();
  });

  const scanA = projectVoxelPoint(scanX, -26, -6, angle, scale, ox, oy);
  const scanB = projectVoxelPoint(scanX, 14, 6, angle, scale, ox, oy);
  context.strokeStyle = "rgba(140, 255, 206, 0.46)";
  context.lineWidth = 2;
  context.setLineDash([6, 8]);
  context.beginPath();
  context.moveTo(scanA.x, scanA.y);
  context.lineTo(scanB.x, scanB.y);
  context.stroke();
  context.setLineDash([]);

  hitCubes
    .sort((a, b) => projectVoxelPoint(a.x, a.y, a.z, angle, scale, ox, oy).depth - projectVoxelPoint(b.x, b.y, b.z, angle, scale, ox, oy).depth)
    .forEach((voxel) => drawStandingCube(context, voxel, angle, scale, ox, oy));
}

function getFieldColumns() {
  if (importedModel) {
    const columns = new Map();
    importedModel.voxels.forEach((voxel) => {
      const key = `${voxel.x},${voxel.y}`;
      const existing = columns.get(key);
      if (existing) {
        existing.minZ = Math.min(existing.minZ, voxel.z);
        existing.maxZ = Math.max(existing.maxZ, voxel.z);
      } else {
        columns.set(key, { x: voxel.x, y: voxel.y, minZ: voxel.z, maxZ: voxel.z });
      }
    });
    return Array.from(columns.values()).map((column) => ({
      ...column,
      depth: Math.max(1, Math.ceil((column.maxZ - column.minZ) / 2)),
    }));
  }
  const columns = [];
  for (let y = -25; y <= 13; y += 1) {
    for (let x = -18; x <= 18; x += 1) {
      const xy = fxy(x, y);
      if (!xy.inside) continue;
      const depth = Math.max(1, Math.round(Number(depthRange.value) / 2 + Math.sin(x * 0.27 + y * 0.31) * 0.7));
      columns.push({ x, y, minZ: -depth, maxZ: depth, depth });
    }
  }
  return columns;
}

function drawVoxelStage() {
  const { context, width, height } = clearStage("voxel");
  const visibleRatio = running ? 0.24 + ((Math.sin(time * 0.78) + 1) / 2) * 0.76 : 1;
  const visible = Math.floor(voxels.length * visibleRatio);
  const angle = 0.72 + time * 0.18;
  const fit = fitVoxelProjection(voxels, angle, width, height, 34);
  const scale = fit.scale;
  const originX = fit.x;
  const originY = fit.y;
  voxelBadge.textContent = `visible: ${visible} / ${voxels.length}`;
  cycleBadge.textContent = `cycle: ${Math.round(visibleRatio * 100)}%`;

  drawVoxelAxes(context, width, height, angle, scale, originX, originY);
  const active = voxels.slice(0, visible).sort((a, b) => {
    return projectVoxelPoint(a.x, a.y, a.z, angle, scale, originX, originY).depth
      - projectVoxelPoint(b.x, b.y, b.z, angle, scale, originX, originY).depth;
  });
  active.forEach((voxel) => drawStandingCube(context, voxel, angle, scale, originX, originY));
}

function fitVoxelProjection(sourceVoxels, angle, width, height, padding = 28) {
  if (!sourceVoxels.length) return { scale: 6, x: width / 2, y: height / 2 };
  const bounds = sourceVoxels.reduce((box, voxel) => ({
    minX: Math.min(box.minX, voxel.x),
    maxX: Math.max(box.maxX, voxel.x),
    minY: Math.min(box.minY, voxel.y),
    maxY: Math.max(box.maxY, voxel.y),
    minZ: Math.min(box.minZ, voxel.z),
    maxZ: Math.max(box.maxZ, voxel.z),
  }), {
    minX: Infinity,
    maxX: -Infinity,
    minY: Infinity,
    maxY: -Infinity,
    minZ: Infinity,
    maxZ: -Infinity,
  });
  const corners = [];
  for (const x of [bounds.minX - 1, bounds.maxX + 1]) {
    for (const y of [bounds.minY - 1, bounds.maxY + 1]) {
      for (const z of [bounds.minZ - 1, bounds.maxZ + 1]) {
        corners.push(projectVoxelPoint(x, y, z, angle, 1, 0, 0));
      }
    }
  }
  const minX = Math.min(...corners.map((point) => point.x));
  const maxX = Math.max(...corners.map((point) => point.x));
  const minY = Math.min(...corners.map((point) => point.y));
  const maxY = Math.max(...corners.map((point) => point.y));
  const spanX = Math.max(1, maxX - minX);
  const spanY = Math.max(1, maxY - minY);
  const scale = Math.max(2.6, Math.min((width - padding * 2) / spanX, (height - padding * 2) / spanY));
  return {
    scale,
    x: width / 2 - ((minX + maxX) * scale) / 2,
    y: height / 2 - ((minY + maxY) * scale) / 2,
  };
}

function projectVoxelPoint(x, y, z, angle, scale, centerX, centerY) {
  const cos = Math.cos(angle);
  const sin = Math.sin(angle);
  const rx = x * cos - z * sin;
  const rz = x * sin + z * cos;
  return {
    x: centerX + rx * scale,
    y: centerY - y * scale + rz * scale * 0.36,
    depth: rz + y * 0.018 + x * 0.002,
  };
}

function drawStandingCube(context, voxel, angle, scale, centerX, centerY) {
  const size = 0.92;
  const corner = (dx, dy, dz) => projectVoxelPoint(
    voxel.x + dx * size,
    voxel.y + dy * size,
    voxel.z + dz * size,
    angle,
    scale,
    centerX,
    centerY,
  );
  const p000 = corner(-0.5, -0.5, -0.5);
  const p100 = corner(0.5, -0.5, -0.5);
  const p010 = corner(-0.5, 0.5, -0.5);
  const p110 = corner(0.5, 0.5, -0.5);
  const p001 = corner(-0.5, -0.5, 0.5);
  const p101 = corner(0.5, -0.5, 0.5);
  const p011 = corner(-0.5, 0.5, 0.5);
  const p111 = corner(0.5, 0.5, 0.5);
  const edge = "rgba(2, 8, 15, 0.32)";

  drawPolygon(context, [p001, p101, p111, p011], darken(voxel.color, 8), edge);
  if (Math.cos(angle) >= 0) {
    drawPolygon(context, [p100, p101, p111, p110], darken(voxel.color, 24), edge);
  } else {
    drawPolygon(context, [p000, p001, p011, p010], darken(voxel.color, 24), edge);
  }
  drawPolygon(context, [p010, p110, p111, p011], lighten(voxel.color, 30), edge);
}

function drawPolygon(context, points, fill, stroke) {
  context.beginPath();
  context.moveTo(points[0].x, points[0].y);
  for (let index = 1; index < points.length; index += 1) context.lineTo(points[index].x, points[index].y);
  context.closePath();
  context.fillStyle = fill;
  context.fill();
  context.strokeStyle = stroke;
  context.lineWidth = 0.65;
  context.stroke();
}

function drawVoxelAxes(context, _width, _height, angle, scale, centerX, centerY) {
  const origin = projectVoxelPoint(-20, -27, -7, angle, scale, centerX, centerY);
  const ax = projectVoxelPoint(1, -27, -7, angle, scale, centerX, centerY);
  const ay = projectVoxelPoint(-20, 2, -7, angle, scale, centerX, centerY);
  const az = projectVoxelPoint(-20, -27, 7, angle, scale, centerX, centerY);
  context.save();
  context.lineWidth = 1.2;
  drawAxisLine(context, origin, ax, "rgba(144, 215, 255, 0.58)", "X");
  drawAxisLine(context, origin, ay, "rgba(140, 255, 206, 0.58)", "Y");
  drawAxisLine(context, origin, az, "rgba(255, 224, 138, 0.58)", "Z");
  context.restore();
}

function drawAxisLine(context, from, to, color, label) {
  context.strokeStyle = color;
  context.fillStyle = color;
  context.beginPath();
  context.moveTo(from.x, from.y);
  context.lineTo(to.x, to.y);
  context.stroke();
  context.font = "11px SFMono-Regular, Consolas, monospace";
  context.fillText(label, to.x + 5, to.y - 5);
}

function parseRgb(color) {
  return color.match(/\d+/g).map(Number);
}

function lighten(color, amount) {
  const [r, g, b] = parseRgb(color);
  return rgb(Math.min(255, r + amount), Math.min(255, g + amount), Math.min(255, b + amount));
}

function darken(color, amount) {
  const [r, g, b] = parseRgb(color);
  return rgb(Math.max(0, r - amount), Math.max(0, g - amount), Math.max(0, b - amount));
}
